default_stages: [prepare-commit-msg, commit]
repos:
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-yaml
